# Generated by Django 3.1.3 on 2020-12-29 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_student_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='board_class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=100, verbose_name='topic')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Description')),
                ('publication_date', models.DateField(default=datetime.date(2020, 12, 29))),
            ],
            options={
                'verbose_name': 'Board_class',
                'verbose_name_plural': 'Board_class',
                'ordering': ['publication_date'],
            },
        ),
        migrations.CreateModel(
            name='board_school',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=100, verbose_name='topic')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Description')),
                ('publication_date', models.DateField(default=datetime.date(2020, 12, 29))),
            ],
            options={
                'verbose_name': 'Board_school',
                'verbose_name_plural': 'Board_school',
                'ordering': ['publication_date'],
            },
        ),
    ]
