# Generated by Django 3.1.3 on 2020-12-31 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20201231_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersprofile',
            old_name='name',
            new_name='first_name',
        ),
    ]
