# Generated by Django 3.1.3 on 2020-12-31 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20201231_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersprofile',
            old_name='first_name',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='usersprofile',
            old_name='last_name',
            new_name='location',
        ),
    ]
