# Generated by Django 3.1.3 on 2020-12-31 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20201231_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='location',
            new_name='email',
        ),
    ]
