# Generated by Django 3.1.3 on 2021-01-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_userprofile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='code',
            new_name='Code',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_name',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='ID_Number',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='num_id',
            new_name='Last_Name',
        ),
    ]
