# Generated by Django 3.1.3 on 2021-01-04 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20210103_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_class',
            name='publication_date',
            field=models.DateField(default=datetime.date(2021, 1, 4)),
        ),
        migrations.AlterField(
            model_name='board_school',
            name='publication_date',
            field=models.DateField(default=datetime.date(2021, 1, 4)),
        ),
    ]
