# Generated by Django 3.1.3 on 2021-01-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20210104_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friday', models.CharField(max_length=100)),
                ('thursday', models.CharField(max_length=100)),
                ('wednesday', models.CharField(max_length=100)),
                ('tuesday', models.CharField(max_length=100)),
                ('monday', models.CharField(max_length=100)),
                ('sunday', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedule',
            },
        ),
    ]
