# Generated by Django 3.1.3 on 2021-01-04 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20210104_1826'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='schedule',
            new_name='schedule_mod',
        ),
    ]
