# Generated by Django 3.1.3 on 2021-01-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20210104_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_mod',
            name='friday_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='schedule_mod',
            name='monday_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='schedule_mod',
            name='sunday_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='schedule_mod',
            name='thursday_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='schedule_mod',
            name='tuesday_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='schedule_mod',
            name='wednesday_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
