# Generated by Django 3.1.3 on 2021-01-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20210105_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='קוד הרשאה'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='First_Name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='שם פרטי'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ID_Number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='תעודת זהות'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Last_Name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='שם משפחה'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
