# Generated by Django 3.1.3 on 2021-01-05 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20210105_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'userprofile'},
        ),
    ]
