# Generated by Django 3.1.3 on 2021-01-06 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20210105_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence_mod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('exist', models.BooleanField(default=False)),
                ('not_exist', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, default=datetime.date(2021, 1, 6), null=True)),
                ('profession', models.CharField(blank=True, max_length=30, null=True)),
                ('hour', models.TimeField(null=True)),
            ],
            options={
                'verbose_name': 'presence',
                'verbose_name_plural': 'presence',
            },
        ),
        migrations.AlterField(
            model_name='board_class',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='תיאור'),
        ),
        migrations.AlterField(
            model_name='board_class',
            name='publication_date',
            field=models.DateField(default=datetime.date(2021, 1, 6), verbose_name='תאריך'),
        ),
        migrations.AlterField(
            model_name='board_class',
            name='topic',
            field=models.CharField(max_length=100, verbose_name='נושא'),
        ),
        migrations.AlterField(
            model_name='board_school',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='תיאור'),
        ),
        migrations.AlterField(
            model_name='board_school',
            name='publication_date',
            field=models.DateField(default=datetime.date(2021, 1, 6), verbose_name='תאריך'),
        ),
        migrations.AlterField(
            model_name='board_school',
            name='topic',
            field=models.CharField(max_length=100, verbose_name='נושא'),
        ),
        migrations.AlterField(
            model_name='schedule_mod',
            name='friday',
            field=models.CharField(max_length=100, verbose_name='יום שישי'),
        ),
        migrations.AlterField(
            model_name='schedule_mod',
            name='friday_link',
            field=models.CharField(max_length=100, verbose_name='קישור-יום שישי'),
        ),
        migrations.AlterField(
            model_name='schedule_mod',
            name='monday',
            field=models.CharField(max_length=100, verbose_name='יום שני'),
        ),
        migrations.AlterField(
            model_name='schedule_mod',
            name='monday_link',
            field=models.CharField(max_length=100, verbose_name='קישור-יום שני'),
        ),
        migrations.AlterField(
            model_name='schedule_mod',
            name='sunday',
            field=models.CharField(max_length=100, verbose_name='יום ראשון'),
        ),
        migrations.AlterField(
            model_name='schedule_mod',
            name='sunday_link',
            field=models.CharField(max_length=100, verbose_name='קישור-יום ראשון'),
        ),
        migrations.AlterField(
            model_name='schedule_mod',
            name='thursday',
            field=models.CharField(max_length=100, verbose_name='יום חמישי'),
        ),
        migrations.AlterField(
            model_name='schedule_mod',
            name='thursday_link',
            field=models.CharField(max_length=100, verbose_name='קישור-יום חמישי'),
        ),
        migrations.AlterField(
            model_name='schedule_mod',
            name='time',
            field=models.CharField(max_length=100, verbose_name='שעה'),
        ),
        migrations.AlterField(
            model_name='schedule_mod',
            name='tuesday',
            field=models.CharField(max_length=100, verbose_name='יום שלישי'),
        ),
        migrations.AlterField(
            model_name='schedule_mod',
            name='tuesday_link',
            field=models.CharField(max_length=100, verbose_name='קישור-יום שלישי'),
        ),
        migrations.AlterField(
            model_name='schedule_mod',
            name='wednesday',
            field=models.CharField(max_length=100, verbose_name='יום רביעי'),
        ),
        migrations.AlterField(
            model_name='schedule_mod',
            name='wednesday_link',
            field=models.CharField(max_length=100, verbose_name='קישור-יום רביעי'),
        ),
        migrations.AlterField(
            model_name='test_schedule',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2021, 1, 6), null=True, verbose_name='תאאריך'),
        ),
        migrations.AlterField(
            model_name='test_schedule',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='שעת סיום'),
        ),
        migrations.AlterField(
            model_name='test_schedule',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='שעת התחלה'),
        ),
    ]
