# Generated by Django 3.1.3 on 2021-01-06 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20210106_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence_mod',
            name='First_Name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='שם פרטי'),
        ),
        migrations.AlterField(
            model_name='presence_mod',
            name='Last_Name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='שם משפחה'),
        ),
        migrations.AlterField(
            model_name='presence_mod',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2021, 1, 6), null=True, verbose_name='תאריך'),
        ),
        migrations.AlterField(
            model_name='presence_mod',
            name='exist',
            field=models.BooleanField(default=False, verbose_name='נוכח'),
        ),
        migrations.AlterField(
            model_name='presence_mod',
            name='hour',
            field=models.TimeField(null=True, verbose_name='שעה'),
        ),
        migrations.AlterField(
            model_name='presence_mod',
            name='not_exist',
            field=models.BooleanField(default=False, verbose_name='לא נוכח'),
        ),
        migrations.AlterField(
            model_name='presence_mod',
            name='profession',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='מקצוע'),
        ),
    ]
