# Generated by Django 3.1.3 on 2021-01-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20210106_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='in_class',
            field=models.BooleanField(default=False, verbose_name='האם נוכח?'),
        ),
    ]
