# Generated by Django 3.1.3 on 2021-01-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_userprofile_in_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='in_class',
            field=models.CharField(choices=[('נוכח', 'נוכח'), ('לא נוכח', 'לא נוכח')], default='לא נוכח', max_length=300, null=True, verbose_name='סטטוס'),
        ),
    ]
