# Generated by Django 3.1.3 on 2021-01-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_userprofile_pro7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pro1',
            field=models.CharField(blank=True, default='לא ניתן ציון', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pro2',
            field=models.CharField(blank=True, default='לא ניתן ציון', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pro3',
            field=models.CharField(blank=True, default='לא ניתן ציון', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pro4',
            field=models.CharField(blank=True, default='לא ניתן ציון', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pro5',
            field=models.CharField(blank=True, default='לא ניתן ציון', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pro6',
            field=models.CharField(blank=True, default='לא ניתן ציון', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pro7',
            field=models.CharField(blank=True, default='לא ניתן ציון', max_length=30, null=True),
        ),
    ]
