# Generated by Django 3.1.3 on 2021-01-09 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_auto_20210106_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_class',
            name='publication_date',
            field=models.DateField(default=datetime.date(2021, 1, 9), verbose_name='תאריך'),
        ),
        migrations.AlterField(
            model_name='board_school',
            name='publication_date',
            field=models.DateField(default=datetime.date(2021, 1, 9), verbose_name='תאריך'),
        ),
        migrations.AlterField(
            model_name='presence_mod',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2021, 1, 9), null=True, verbose_name='תאריך'),
        ),
        migrations.AlterField(
            model_name='test_schedule',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2021, 1, 9), null=True, verbose_name='תאאריך'),
        ),
    ]
