# Generated by Django 3.1.3 on 2021-01-09 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_userprofile_email_rec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_rec',
        ),
    ]
