# Generated by Django 3.1.3 on 2021-01-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_remove_userprofile_email_rec'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_rec',
            field=models.CharField(blank=True, default='<django.db.models.query_utils.DeferredAttribute object at 0x0000010B828BA790>', max_length=30, null=True),
        ),
    ]
