# Generated by Django 3.1.3 on 2021-01-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_auto_20210109_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_class',
            name='publication_date',
            field=models.DateField(default='<function now at 0x0000023591B6AA60>', verbose_name='תאריך'),
        ),
        migrations.AlterField(
            model_name='board_school',
            name='publication_date',
            field=models.DateField(default='<function now at 0x0000023591B6AA60>', verbose_name='תאריך'),
        ),
        migrations.AlterField(
            model_name='presence_mod',
            name='date',
            field=models.DateField(blank=True, default='2021-01-09 16:25:47.450525+00:00', null=True, verbose_name='תאריך'),
        ),
        migrations.AlterField(
            model_name='test_schedule',
            name='date',
            field=models.DateField(blank=True, default='2021-01-09 16:25:47.450029+00:00', null=True, verbose_name='תאאריך'),
        ),
    ]
