# Generated by Django 3.1.3 on 2021-01-09 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_auto_20210109_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_schedule',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2021, 1, 9), null=True, verbose_name='תאאריך'),
        ),
    ]
