# Generated by Django 3.1.3 on 2021-01-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_auto_20210109_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_school',
            name='publication_date',
            field=models.DateField(default='2021-01-09', verbose_name='תאריך'),
        ),
        migrations.AlterField(
            model_name='test_schedule',
            name='end_time',
            field=models.CharField(max_length=10, verbose_name='שעת סיום'),
        ),
        migrations.AlterField(
            model_name='test_schedule',
            name='start_time',
            field=models.CharField(max_length=10, verbose_name='שעת התחלה'),
        ),
    ]
