# Generated by Django 3.1.3 on 2021-01-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_auto_20210109_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_schedule',
            name='start_time',
            field=models.CharField(blank=True, default='12:00', max_length=30, null=True, verbose_name='שעת התחלה'),
        ),
    ]
