# Generated by Django 3.1.3 on 2021-01-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_auto_20210109_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence_mod',
            name='date',
            field=models.DateField(blank=True, default='2021-01-09', null=True, verbose_name='תאריך'),
        ),
    ]
